name: "Retail_Application"
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^1.1.6

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  go_router: ^10.0.0
  dio: ^5.4.1
  http: ^1.2.2 
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
  intl: ^0.20.2
  provider: ^6.0.5
  go_router: ^10.0.0
  dio: ^5.4.1

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/Icon.png

flutter:
  assets:
    - assets/images/
    - assets/mock/
    - assets/alerts/
    - mock/
    - mock/products/
    - mock/mock_datas/

  uses-material-design: true
  generate: true
